### ISSUE TITLE
A "remove"/"rm" subcommand.

### ISSUE THREAD

**Issue by dontlaugh** [naggie/dstask#22]
Awesome tool. Git sync is really easy (when compared to running a taskwarrior server).

Could you add a "remove" command? This could simply mask a task from view but not really purge it, like taskwarrior does.

This command is important for computing statistics for burndown charts. Sometimes you add things by mistake, or need to consolidate tasks, but don't want to say they're "done".

**Comment by naggie** [comment]
Thanks.

I think you're right, I've thought about adding a delete command that would destroy the task as if it never existed with `git rm`. Would this work for what you need?

**Comment by dontlaugh** [comment]
I think so. This would be different than taskwarrior's behavior, I think. But I've never found the need for a "soft delete" in a personal task manager. So this gets a thumbs up :+1: from me.

**Comment by dontlaugh** [comment]
I have implemented this with #26 but it is a WIP because I have some questions.

1. There should only be one file to `git rm` at any time, right? e.g. files are transitioned between directories, so I can just use their `task.Status` and their `task.UUID` to locate them on disk?
2. What is the gob database? I am not making any deletes from there yet. Should I?

**Comment by naggie** [comment]
Now in master. Sorry, missed your questions:


 >  There should only be one file to git rm at any time, right? e.g. files are transitioned between directories, so I can just use their task.Status and their task.UUID to locate them on disk?

Yes, by design and `task.SaveToDisk()` makes sure there is only one copy as bad manual merges could cause more than one.

>    What is the IdsMap gob database? I am not making any deletes from there yet. Should I?

That's a local cache of numeric ID to UUID, updated automatically. Tasks used to record their own preferred numeric ID, which was great as it allowed mostly consistent numeric IDs across hosts; however sometimes it caused merge conflicts so now I maintain the db.
