### ISSUE TITLE
Issues with dstask import-tw (or maybe with task export)

### ISSUE THREAD

**Issue by axelsimon** [naggie/dstask#23]
Hi,
First of all, thanks for making dstask. Having a drop-in replacement for taskwarrior that uses a sane sync mechanism is great.

I have discovered that some information has been lost in my transition from taskwarrior to dstask:
- all tags have been made lowercase
- old tags not used by current tasks have disappeared. This might actually be a good thing in my specific case, but it's still surprising.
- annotations have lost their date. This is quite an inconvenience, as I have tasks with stuff like "reminder sent yesterday" which now make no sense, as they have no date attached.

It also appears that calling `(ds)task completed` or `task all` after doing the initial git repo initialisation + import doesn't show any tasks. However, checking the `.dstask/resolved` directory shows lots of files corresponding to tasks in there.

Is `dstask import-tw` dropping some of the attributes on import, or is it limitations of taskwarrior's `task export` command?

Thanks!

**Comment by naggie** [comment]
> First of all, thanks for making dstask. Having a drop-in replacement for taskwarrior that uses a sane sync mechanism is great.

You're welcome, that's nice to hear.

> all tags have been made lowercase

Yes, this is a design decision for consistency

> old tags not used by current tasks have disappeared. This might actually be a good thing in my specific case, but it's still surprising.
Yes, I didn't want old tags to accumulate. Also it would probably require a caching layer as it would require loading all resolved tasks which does not happen by default; resolved tasks pile up quickly (I have 5000 or so) other tasks are more controlled assuming you're a productive person :)


> annotations have lost their date. This is quite an inconvenience, as I have tasks with stuff like "reminder sent yesterday" which now make no sense, as they have no date attached.

This is due to the fact that dstask doesn't do logged annotations. Rather it keeps a markdown document for every task. Perhaps, during the conversion the date could be encoded into the markdown? It wouldn't add a date thereafter, though it would be possible using the note command in argument mode, eg `dstask 12 note foo bar` might result in `11:09 25-Jun-2020 foo bar` in the file.


> It also appears that calling (ds)task completed or task all after doing the initial git repo initialisation + import doesn't show any tasks. However, checking the .dstask/resolved directory shows lots of files corresponding to tasks in there.

That's right, command have slightly different names in some cases. `dstask show-resolved` is what you're after -- a long command but not so with the bash/zsh completion. Have you enabled the completion?
